import Head from 'next/head'
import { Navigation } from './components/navigation'
import "./globals.css"
import "../../public/fonts.css"
import style from "./page.module.css"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, pagina }) {
  return (
    <html lang="en"> 
      <Head>
        
        <title>Portfolio Igna Luna</title>
        <meta name="description" content="Programador Full Stack" />
      </Head>
      <body>
        <Navigation></Navigation>
        <div className={style.content}>{children}</div>
      </body>
    </html>
  )
}
